output = "/app/models"

[mysql]
  dbname  = "go-vue-sandbox_development"
  host    = "mysql"
  port    = "3306"
  user    = "root"
  pass    = ""
  sslmode = "false"
  blacklist = ["gorp_migrations"]
