development:
  dialect: mysql
  dir: db/migrations
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/go-vue-sandbox_development?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true

test:
  dialect: mysql
  dir: db/migrations
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/go-vue-sandbox_test?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true

production:
  dialect: mysql
  dir: db/migrations
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
